version: "3"

services:
  langflow:
    image: logspace/langflow:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "172.17.0.1:4545:7860"
    command: langflow run --host 0.0.0.0
