version: "3.8"

services:
  langflow:
    image: langflowai/langflow:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - "172.17.0.1:21273:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - LANGFLOW_CONFIG_DIR=/var/lib/langflow
      - LANGFLOW_SUPERUSER=${LANGFLOW_SUPERUSER}
      - LANGFLOW_SUPERUSER_PASSWORD=${ADMIN_PASSWORD}
      - LANGFLOW_AUTO_LOGIN=False
      - LANGFLOW_SECRET_KEY=${LANGFLOW_SECRET_KEY}
      - LANGFLOW_NEW_USER_IS_ACTIVE=False
    volumes:
      - ./langflow-data:/var/lib/langflow:rw

  postgres:
    image: elestio/postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "172.17.0.1:40211:5432"
    volumes:
      - ./langflow-postgres:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:46214:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
